package Model;
// Generated May 4, 2024 4:11:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudante generated by hbm2java
 */
public class Estudante  implements java.io.Serializable {


     private Integer nrMatricula;
     private Curso curso;
     private Turma turma;
     private String nome;
     private String apelido;
     private String endereco;
     private String contacto;
     private Set realizas = new HashSet(0);

    public Estudante() {
    }

    public Estudante(Curso curso, Turma turma, String nome, String apelido, String endereco, String contacto, Set realizas) {
       this.curso = curso;
       this.turma = turma;
       this.nome = nome;
       this.apelido = apelido;
       this.endereco = endereco;
       this.contacto = contacto;
       this.realizas = realizas;
    }
   
    public Integer getNrMatricula() {
        return this.nrMatricula;
    }
    
    public void setNrMatricula(Integer nrMatricula) {
        this.nrMatricula = nrMatricula;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public Set getRealizas() {
        return this.realizas;
    }
    
    public void setRealizas(Set realizas) {
        this.realizas = realizas;
    }




}


